image: node:10.12.0 # change to match your node version

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - functions/node_modules/

before_script:
  - cd functions
  - npm install
  - cd ../
  - npm install
  - npm install -g firebase-tools

pages:
  stage: deploy
  environment: production
  script:
    - npm run build
    - rm build/static/*/*.map
    - firebase deploy --token "1/f9b4HPBcOHopxo_kshNSTF4l4OsrupPJm9s6TGhbm1IeK10OamyH7lPVHP7sYyjs" -P jamgph
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public

  only:
    - master # run on master branch
