image: node:10.12.0 # change to match your node version

cache:
  key: cache_npm
  paths:
    - .cache_npm
    # - node_modules/
    # - functions/node_modules/
    # - /usr/local/bin/firebase/

before_script:
  - cd functions
  - npm install
  - cd ../
  - npm install
  - npm install -g firebase-tools

pages:
  stage: deploy
  environment: production
  script:
    - npm run build
    - rm build/static/*/*.map
    - firebase deploy --token "1/lDwQGJGXmSKvRIONgzDs2s9I2suC5Km2N7r6GN9b4NSNQL1v2pVtshoHlBUGnnRK" -P jamgph
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public

  only:
    - master # run on master branch
