image: node:10.12.0 # change to match your node version

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - npm install -g firebase-tools
  - npm install -g firebase-functions

pages:
  stage: deploy
  environment: production
  script:
    - npm run build
    - firebase deploy --token "1/lDwQGJGXmSKvRIONgzDs2s9I2suC5Km2N7r6GN9b4NSNQL1v2pVtshoHlBUGnnRK" -P jamgph
  only:
    - master # run on master branch
