image: node:10.12.0 # change to match your node version

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - CI=true npm test

pages:
  stage: deploy
  script:
    - CI=true npm run build
  artifacts:
    paths:
      - build # GitLab pages serve from a 'public' directory
  only:
    - master # run on master branch